/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cryptoutils;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class CryptoUtilsTest {
    @Test
    public void sameMessageResult() {
        byte[] m1="carlota".getBytes();
        byte[] m2="carlota".getBytes();

        String res1= String.valueOf(CryptoUtils.Hash(m1));
        String res2= String.valueOf(CryptoUtils.Hash(m2));

        assertEquals(res1,res2);
    }
}
