/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cryptoutils;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        CryptoUtils classUnderTest = new CryptoUtils();
        

        assertTrue("someLibraryMethod should return 'true'", classUnderTest.Hash());
    }
}
